### ISSUE TITLE
Have the <div> wrap *all* related elements

### ISSUE THREAD

**Issue by sdhunt** [Daryl6222/prj-rev-bwfs-dasmoto#2]
https://github.com/Daryl6222/prj-rev-bwfs-dasmoto/blob/8dfd6c8280f9fd07a05b6a3185a331694e0e48d6/Dasmoto/index.html#L14-L20

Note that, logically, the heading, the image, the subheading and the paragraph text are all part of the same "structure"... it makes more sense to have the "wrapper" `<div>` surround (be the parent of) all of those elements. This also provides the opportunity to give a common class to that `<div>`, so that all such divs can be targeted by the same CSS rules. For example:

```
  <div class="brushes section">
    <h2>Brushes</h2>
    <img src="./images/hacksaw.jpeg" alt="paint brushes" />
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality ... </p>
  </div>
```
and CSS rules for _common_ styles...
```
.section h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
and for _unique_ styles...
```
.brushes {
  background-color: mediumspringgreen;
}
```

Note that the value of a `class` attribute is interpreted as a _space-delimited-list_ of class names; hence `class="brushes section"` means, apply the `brushes` class and the `section` class.

**Comment by Daryl6222** [comment]
Got it
