### ISSUE TITLE
Do NOT use inline styles

### ISSUE THREAD

**Issue by sdhunt** [Daryl6222/prj-rev-bwfs-dasmoto#3]
https://github.com/Daryl6222/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L20
https://github.com/Daryl6222/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L29
https://github.com/Daryl6222/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L38

Do **not** use inline styles; the whole point of using a stylesheet is to _separate_ style from structure.
```
 ... sizes. <span style="color:blue;font-weight:bold;">Starting at $3.00 / brush.</span></p>
```

Define a `class` for the span element, giving it a name describing _what_ is being styled:
```
 ... sizes. <span class="pricing">Starting at $3.00 / brush.</span></p>
```
with an appropriate CSS rule to apply the required style:
```
.pricing {
  font-weight: bold;
  color: blue;
}
```

**Comment by Daryl6222** [comment]
Makes sense, I appreciate the clarity.
