### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [Daryl6222/prj-rev-bwfs-dasmoto#5]
_Grade:_ **Meets Expectations**

Nice work creating a web page that accurately follows the project specification. Good job remembering to define `alt` text for the images, for those viewers who have _accessibility enabled_.

What the page _looks_ like is only half the story.  Having well structured, readable, concise, and duplication-free source code is also very important. You've definitely made a good start in this direction.

Things to pay attention to: 
* Remember to use the full HTML entity code for ampersands
* Do **NOT** use inline styles: define a class in the CSS file and define the style there
* Group related elements within "wrapper" divs

Further Reading: 
* https://learn.shayhowe.com/html-css/writing-your-best-code/

Keep up the good work.

**Comment by Daryl6222** [comment]
Thank you!
